language: node_js
node_js:
 - "node"
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
- secure: "TsYgfDTXM9DhteoxruftAIm9qbcVFTfBbPmi/Mv9lGkDKZ/b4pputXgbfy2On7dsu5s9Bio/P4Nri61sgVHZm6AJIsNWf2D6Ggiz94oddr0r+7dPp9yqTziPQAKNmMSzCtLff9Dl4BSOiasy/aQy5M+NrD6kXex0xjZyTIEndzk="
script:
  - npm install
  - rsync node_modules + ./hello.js as1 as2 as3 a4...
  - ssh as1 as2 as3 as4 .. service restart myapp or ./restart_myapp.sh
